# Generated by Django 5.2.6 on 2025-10-09 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.IntegerField(verbose_name='Номер площадки')),
                ('zone_type', models.CharField(choices=[('forest', 'Лес'), ('meadow', 'Луг')], max_length=10, verbose_name='Тип местности')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер площадки (м²)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата создания площадки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Долгота')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('mapped_point', models.CharField(blank=True, max_length=100, null=True, verbose_name='Привязка к карте')),
                ('mapped_point_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расстояние от точки привязки (м)')),
                ('mapped_point_azimuth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Азимут от точки привязки (°)')),
                ('forestry_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название лесничества')),
                ('center_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расстояние от центра (м)')),
                ('center_azimuth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Азимут от центра (°)')),
                ('mesorelief_shape', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма мезорельефа')),
                ('exposition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Экспозиция склона')),
                ('steepness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Крутизна склона (°)')),
                ('position_relief', models.CharField(blank=True, max_length=100, null=True, verbose_name='Положение в рельефе')),
                ('microrelief_shape', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма микрорельефа')),
                ('humidification_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип увлажнения')),
                ('groundwater_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень грунтовых вод')),
                ('brushwood_compos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Состав валежника')),
                ('brushwood_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Диаметр валежника (см)')),
                ('brushwood_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество валежника')),
                ('decomposition_degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Степень разложения подстилки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'db_table': 'bio_sites',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вида')),
                ('author', models.CharField(max_length=255, verbose_name='Автор вида')),
                ('lLight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала относительной освещенности (Landolt)')),
                ('lTemperature', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала теплолюбивости (Landolt)')),
                ('lContinentality', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала континентальности (Landolt)')),
                ('lMoisture', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала влажности (Landolt)')),
                ('lReaction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала кислотности почвы (Landolt)')),
                ('lNutrient', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала обеспеченности почвы минеральным азотом (Landolt)')),
                ('lHumus', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала гумуса (Landolt)')),
                ('lDispersion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала дисперсии (Landolt)')),
                ('eLight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала относительной освещенности (Ellenberg)')),
                ('eTemperature', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала теплолюбивости (Ellenberg)')),
                ('eContinentality', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала континентальности (Ellenberg)')),
                ('eMoisture', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала влажности (Ellenberg)')),
                ('eReaction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала кислотности почвы (Ellenberg)')),
                ('eNutrient', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала обеспеченности почвы минеральным азотом (Ellenberg)')),
                ('tm1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала термоклиматическая минимум (Цыганов)')),
                ('tm2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала термоклиматическая максимум (Цыганов)')),
                ('kn1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала континентальности климата минимум (Цыганов)')),
                ('kn2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала континентальности климата максимум (Цыганов)')),
                ('om1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала влажности климата минимум (Цыганов)')),
                ('om2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала влажности климата максимум (Цыганов)')),
                ('cr1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала морозности климата минимум (Цыганов)')),
                ('cr2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала морозности климата максимум (Цыганов)')),
                ('hd1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала увлажнения почвы минимум (Цыганов)')),
                ('hd2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала увлажнения почвы максимум (Цыганов)')),
                ('tr1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала солевого режима почвы минимум (Цыганов)')),
                ('tr2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала солевого режима почвы максимум (Цыганов)')),
                ('nt1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала обеспеченности почвы минеральным азотом минимум (Цыганов)')),
                ('nt2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала обеспеченности почвы минеральным азотом максимум (Цыганов)')),
                ('rc1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала кислотности почвы минимум (Цыганов)')),
                ('rc2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала кислотности почвы максимум (Цыганов)')),
                ('lc1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала освещенности минимум (Цыганов)')),
                ('lc2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала освещенности максимум (Цыганов)')),
                ('fh1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала переменности увлажнения минимум (Цыганов)')),
                ('fh2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шкала переменности увлажнения максимум (Цыганов)')),
                ('raunkiaer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Жизненная форма по Раункиеру')),
                ('serebryakov', models.CharField(blank=True, max_length=10, null=True, verbose_name='Жизненная форма по Серебрякову')),
                ('ecobiomorphs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Экобиоморфа')),
                ('geoelements', models.CharField(blank=True, max_length=10, null=True, verbose_name='Геоэлемент')),
                ('ta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип ареала')),
            ],
            options={
                'verbose_name': 'Вид растения',
                'verbose_name_plural': 'Виды растений',
                'db_table': 'bio_species',
                'constraints': [models.UniqueConstraint(fields=('title', 'author'), name='unique_title_author')],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(blank=True, choices=[('', 'Нет'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=3, verbose_name='Ярус')),
                ('abundance', models.CharField(choices=[('r', 'Единично'), ('+', 'До 1%'), ('1', 'До 5%'), ('2', '5-25%'), ('3', '25-50%'), ('4', '50-75%'), ('5', '75-100%')], max_length=3, verbose_name='Обилие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.site', verbose_name='Площадка')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.species', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Описание вида',
                'verbose_name_plural': 'Описания видов',
                'db_table': 'bio_descriptions',
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['user', 'site_number', 'zone_type'], name='bio_sites_user_id_0bdabd_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('user', 'site_number', 'zone_type'), name='unique_user_site_zone'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['user', 'species', 'site'], name='bio_descrip_user_id_e0ad54_idx'),
        ),
        migrations.AddConstraint(
            model_name='description',
            constraint=models.UniqueConstraint(fields=('user', 'species', 'site', 'tier'), name='unique_description'),
        ),
    ]
