# Generated by Django 5.2.6 on 2025-10-13 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_load_species_data_from_csv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('species_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вида')),
                ('author', models.CharField(max_length=255, verbose_name='Автор вида')),
                ('latin_name', models.CharField(db_index=True, max_length=255, verbose_name='Латинское название')),
                ('taxon_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип таксона')),
                ('conservation_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Охранный статус')),
                ('habitat_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип местообитания')),
                ('diet_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип питания')),
                ('life_span', models.CharField(blank=True, max_length=100, null=True, verbose_name='Продолжительность жизни')),
                ('migration_pattern', models.CharField(blank=True, max_length=255, null=True, verbose_name='Миграции')),
                ('tax_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Класс')),
                ('tax_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отряд')),
                ('tax_family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Семейство')),
                ('animal_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип животного (vertebrate/invertebrate)')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
                'db_table': 'bio_zoology_species',
                'constraints': [models.UniqueConstraint(fields=('latin_name', 'author'), name='unique_animal_latin_author')],
            },
        ),
        migrations.CreateModel(
            name='AnimalPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(blank=True, null=True, verbose_name='Дата наблюдения')),
                ('estimated_count', models.IntegerField(blank=True, null=True, verbose_name='Оценка численности')),
                ('density', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Плотность')),
                ('age_structure', models.JSONField(blank=True, null=True, verbose_name='Возрастная структура')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.site', verbose_name='Площадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('animal_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.animalspecies', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Популяция животных',
                'verbose_name_plural': 'Популяции животных',
                'db_table': 'bio_zoology_populations',
            },
        ),
        migrations.CreateModel(
            name='AnimalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время наблюдения')),
                ('gender', models.CharField(blank=True, max_length=32, null=True, verbose_name='Пол')),
                ('age', models.CharField(blank=True, max_length=32, null=True, verbose_name='Возраст')),
                ('behavior', models.TextField(blank=True, null=True, verbose_name='Поведение')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.site', verbose_name='Площадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('population', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.animalpopulation', verbose_name='Связанная популяция')),
                ('animal_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.animalspecies', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Наблюдение животного',
                'verbose_name_plural': 'Наблюдения животных',
                'db_table': 'bio_zoology_observations',
            },
        ),
        migrations.CreateModel(
            name='EcologicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профиля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Экологический профиль',
                'verbose_name_plural': 'Экологические профили',
                'db_table': 'bio_ecoprofiles_profiles',
            },
        ),
        migrations.CreateModel(
            name='FloristicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Флористический список',
                'verbose_name_plural': 'Флористические списки',
                'db_table': 'bio_floristics_lists',
            },
        ),
        migrations.CreateModel(
            name='FloristicListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.CharField(blank=True, choices=[('r', 'Единично'), ('+', 'До 1%'), ('1', 'До 5%'), ('2', '5-25%'), ('3', '25-50%'), ('4', '50-75%'), ('5', '75-100%')], max_length=3, null=True, verbose_name='Обилие')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bio.floristiclist', verbose_name='Список')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.species', verbose_name='Вид растения')),
            ],
            options={
                'verbose_name': 'Элемент флористического списка',
                'verbose_name_plural': 'Элементы флористического списка',
                'db_table': 'bio_floristics_items',
            },
        ),
        migrations.CreateModel(
            name='PollenSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='Идентификатор образца')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='Дата отбора')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Глубина')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Долгота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Образец пыльцы',
                'verbose_name_plural': 'Образцы пыльцы',
                'db_table': 'bio_paleobotany_samples',
            },
        ),
        migrations.CreateModel(
            name='PollenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bio/paleobotany/', verbose_name='Файл')),
                ('magnification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Увеличение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio.pollensample', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'Изображение образца пыльцы',
                'verbose_name_plural': 'Изображения образцов пыльцы',
                'db_table': 'bio_paleobotany_images',
            },
        ),
        migrations.CreateModel(
            name='ProfileSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_start', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расстояние от начала (м)')),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота (м)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sites', to='bio.ecologicalprofile', verbose_name='Профиль')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.site', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Площадка профиля',
                'verbose_name_plural': 'Площадки профиля',
                'db_table': 'bio_ecoprofiles_profile_sites',
            },
        ),
        migrations.CreateModel(
            name='SoilProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100, verbose_name='Идентификатор профиля')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Долгота')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Глубина разреза (см)')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='Дата отбора')),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип почвы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.site', verbose_name='Площадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Почвенный профиль',
                'verbose_name_plural': 'Почвенные профили',
                'db_table': 'bio_geomorphology_profiles',
            },
        ),
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Глубина от (см)')),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Глубина до (см)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('texture', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текстура')),
                ('structure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Структура')),
                ('moisture', models.CharField(blank=True, max_length=50, null=True, verbose_name='Влажность')),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pH')),
                ('organic_matter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Орг. вещество (%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='bio.soilprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Почвенный слой',
                'verbose_name_plural': 'Почвенные слои',
                'db_table': 'bio_geomorphology_layers',
            },
        ),
        migrations.CreateModel(
            name='SoilProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bio/geomorphology/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bio.soilprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Изображение почвенного профиля',
                'verbose_name_plural': 'Изображения почвенных профилей',
                'db_table': 'bio_geomorphology_images',
            },
        ),
        migrations.CreateModel(
            name='SpeciesInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('predation', 'predation'), ('pollination', 'pollination'), ('seed_dispersal', 'seed_dispersal'), ('parasitism', 'parasitism'), ('commensalism', 'commensalism'), ('mutualism', 'mutualism'), ('competition', 'competition'), ('habitat', 'habitat'), ('food', 'food'), ('other', 'other')], max_length=32, verbose_name='Тип взаимодействия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('observed_date', models.DateField(blank=True, null=True, verbose_name='Дата наблюдения')),
                ('animal_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.animalspecies', verbose_name='Вид животного')),
                ('plant_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.species', verbose_name='Вид растения')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.site', verbose_name='Площадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие видов',
                'verbose_name_plural': 'Взаимодействия видов',
                'db_table': 'bio_interactions_records',
            },
        ),
        migrations.CreateModel(
            name='Succession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('succession_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип сукцессии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.site', verbose_name='Площадка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сукцессия',
                'verbose_name_plural': 'Сукцессии',
                'db_table': 'bio_successions',
            },
        ),
        migrations.CreateModel(
            name='SuccessionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField(verbose_name='Номер стадии')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (годы)')),
                ('succession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='bio.succession', verbose_name='Сукцессия')),
            ],
            options={
                'verbose_name': 'Стадия сукцессии',
                'verbose_name_plural': 'Стадии сукцессии',
                'db_table': 'bio_succession_stages',
            },
        ),
        migrations.CreateModel(
            name='SuccessionSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.CharField(blank=True, choices=[('r', 'Единично'), ('+', 'До 1%'), ('1', 'До 5%'), ('2', '5-25%'), ('3', '25-50%'), ('4', '50-75%'), ('5', '75-100%')], max_length=3, null=True, verbose_name='Обилие')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('plant_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.species', verbose_name='Вид растения')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_species', to='bio.successionstage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Вид на стадии сукцессии',
                'verbose_name_plural': 'Виды на стадиях сукцессии',
                'db_table': 'bio_succession_species',
            },
        ),
        migrations.AddIndex(
            model_name='animalpopulation',
            index=models.Index(fields=['user', 'site'], name='bio_zoology_user_id_fdb20e_idx'),
        ),
        migrations.AddIndex(
            model_name='animalpopulation',
            index=models.Index(fields=['animal_species'], name='bio_zoology_animal__51bd48_idx'),
        ),
        migrations.AddIndex(
            model_name='animalobservation',
            index=models.Index(fields=['user', 'site'], name='bio_zoology_user_id_9275e5_idx'),
        ),
        migrations.AddIndex(
            model_name='animalobservation',
            index=models.Index(fields=['animal_species'], name='bio_zoology_animal__0c9187_idx'),
        ),
        migrations.AddConstraint(
            model_name='floristiclistitem',
            constraint=models.UniqueConstraint(fields=('list', 'species'), name='unique_list_species'),
        ),
        migrations.AddIndex(
            model_name='pollensample',
            index=models.Index(fields=['user', 'sample_id'], name='bio_paleobo_user_id_d4f990_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollensample',
            constraint=models.UniqueConstraint(fields=('user', 'sample_id'), name='unique_user_sample_id'),
        ),
        migrations.AddIndex(
            model_name='profilesite',
            index=models.Index(fields=['profile'], name='bio_ecoprof_profile_0e9384_idx'),
        ),
        migrations.AddIndex(
            model_name='profilesite',
            index=models.Index(fields=['site'], name='bio_ecoprof_site_id_8ddd00_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilesite',
            constraint=models.UniqueConstraint(fields=('profile', 'site'), name='unique_profile_site'),
        ),
        migrations.AddIndex(
            model_name='soilprofile',
            index=models.Index(fields=['user', 'profile_id'], name='bio_geomorp_user_id_6dc453_idx'),
        ),
        migrations.AddConstraint(
            model_name='soilprofile',
            constraint=models.UniqueConstraint(fields=('user', 'profile_id'), name='unique_user_profile_id'),
        ),
        migrations.AddIndex(
            model_name='soillayer',
            index=models.Index(fields=['profile'], name='bio_geomorp_profile_4a99f3_idx'),
        ),
        migrations.AddIndex(
            model_name='speciesinteraction',
            index=models.Index(fields=['user', 'site'], name='bio_interac_user_id_e440be_idx'),
        ),
        migrations.AddIndex(
            model_name='speciesinteraction',
            index=models.Index(fields=['plant_species'], name='bio_interac_plant_s_077c43_idx'),
        ),
        migrations.AddIndex(
            model_name='speciesinteraction',
            index=models.Index(fields=['animal_species'], name='bio_interac_animal__1e9601_idx'),
        ),
        migrations.AddConstraint(
            model_name='successionstage',
            constraint=models.UniqueConstraint(fields=('succession', 'stage_number'), name='unique_succession_stage_number'),
        ),
        migrations.AddConstraint(
            model_name='successionspecies',
            constraint=models.UniqueConstraint(fields=('stage', 'plant_species'), name='unique_stage_plant_species'),
        ),
    ]
