# Generated by Django 5.2.6 on 2025-10-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_animalspecies_animalpopulation_animalobservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalspecies',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вида'),
        ),
    ]
